Fix Groq API key deployment

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -9,7 +9,6 @@ on:
 
   workflow_dispatch:
 
-# Prevent two deployments from running at the same time
 concurrency:
   group: agentic-chatbot-production
   cancel-in-progress: true
@@ -101,7 +100,7 @@ jobs:
     steps:
 
       # --------------------------------------------------------
-      # Login to Docker Hub
+      # Docker Hub Login
       # --------------------------------------------------------
       - name: Log in to Docker Hub
         uses: docker/login-action@v4
@@ -115,6 +114,7 @@ jobs:
       # --------------------------------------------------------
       - name: Validate application secrets
         env:
+          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
           GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
           TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
           OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
@@ -124,6 +124,11 @@ jobs:
           LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
 
         run: |
+          if [ -z "$GROQ_API_KEY" ]; then
+            echo "GROQ_API_KEY secret is missing."
+            exit 1
+          fi
+
           if [ -z "$GOOGLE_API_KEY" ]; then
             echo "GOOGLE_API_KEY secret is missing."
             exit 1
@@ -189,6 +194,7 @@ jobs:
         env:
           IMAGE_PATH: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}
 
+          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
           GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
           TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
@@ -204,6 +210,7 @@ jobs:
             --restart unless-stopped \
             --name agentic-chatbot \
             -p 8501:8501 \
+            -e GROQ_API_KEY \
             -e OPENAI_API_KEY \
             -e GOOGLE_API_KEY \
             -e TAVILY_API_KEY \
@@ -238,8 +245,7 @@ jobs:
 
           echo "The Streamlit container is running."
 
-          docker ps \
-            --filter "name=^agentic-chatbot$"
+          docker ps --filter "name=^agentic-chatbot$"
 
 
       # --------------------------------------------------------
